-- 코드를 입력하세요
SELECT ORD.YEAR
    , ORD.MONTH
    , COUNT(DISTINCT USR.USER_ID) PUCHASED_USERS
    , ROUND(COUNT(DISTINCT USR.USER_ID) / USR_CNT.CNT,1) PUCHASED_RATIO
FROM (    
SELECT USER_ID
FROM USER_INFO
WHERE YEAR(JOINED) = '2021'
) USR
INNER JOIN (
SELECT DISTINCT USER_ID
    , YEAR(SALES_DATE) YEAR
    , MONTH(SALES_DATE) MONTH
FROM ONLINE_SALE
) ORD
ON USR.USER_ID = ORD.USER_ID
JOIN (    
SELECT COUNT(USER_ID) CNT
FROM USER_INFO
WHERE YEAR(JOINED) = '2021'
) USR_CNT
GROUP BY ORD.YEAR
    , ORD.MONTH
    