-- 코드를 입력하세요
SELECT BOOK.CATEGORY
    , SUM(BOOK_SALES.SALES) TOTAL_SALES
FROM BOOK
INNER JOIN BOOK_SALES
ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
AND DATE_FORMAT(BOOK_SALES.SALES_DATE, '%Y%m') = '202201'
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY 