-- 코드를 입력하세요
SELECT BOOK.AUTHOR_ID
    , AUTHOR.AUTHOR_NAME
    , BOOK.CATEGORY
    , SUM(BOOK.PRICE * BOOK_SALES.SALES) TOTAL_SALES
FROM BOOK
INNER JOIN
    (
        SELECT AUTHOR_ID
            , AUTHOR_NAME
        FROM AUTHOR
    ) AUTHOR
ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
INNER JOIN
    (
        SELECT BOOK_ID
            , SALES
        FROM BOOK_SALES
        WHERE DATE_FORMAT(SALES_DATE, '%Y%m') = '202201'
    ) BOOK_SALES
ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
GROUP BY BOOK.AUTHOR_ID, BOOK.CATEGORY
ORDER BY BOOK.AUTHOR_ID, BOOK.CATEGORY DESC
