-- 코드를 입력하세요
SELECT HISTORY_ID
    , ROUND(IFNULL(100-DISCOUNT.DISCOUNT_RATE, 100) * DAILY_FEE * TERM / 100) FEE
FROM (
        SELECT HISTORY.HISTORY_ID
            , CASE WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE)+1 >= 90 THEN '90일 이상'
                   WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE)+1 >= 30 THEN '30일 이상'
                   WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE)+1 >= 7 THEN '7일 이상'
                ELSE '' END DURATION_TYPE
            , DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE)+1 TERM
            , FEE.DAILY_FEE
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
        INNER JOIN (
                    SELECT CAR_ID
                        , DAILY_FEE
                    FROM CAR_RENTAL_COMPANY_CAR
                    WHERE CAR_TYPE = '트럭'
        ) FEE
        ON HISTORY.CAR_ID = FEE.CAR_ID
) HISTORY
LEFT OUTER JOIN (
                    SELECT DURATION_TYPE
                        , DISCOUNT_RATE
                    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                    WHERE CAR_TYPE = '트럭'
) DISCOUNT
ON HISTORY.DURATION_TYPE = DISCOUNT.DURATION_TYPE
ORDER BY ROUND(IFNULL(100-DISCOUNT.DISCOUNT_RATE, 100) * DAILY_FEE * TERM / 100) DESC
    , HISTORY_ID DESC

